# Generated by Django 4.2.13 on 2024-05-09 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(unique=True)),
                ('longitude', models.FloatField(unique=True)),
                ('height', models.FloatField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35, unique=True)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('winter', 'Зима'), ('spring', 'Весна'), ('summer', 'Лето'), ('autumn', 'Осень')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Иван', max_length=50)),
                ('father_name', models.CharField(blank=True, default='Иванович', max_length=50)),
                ('surname', models.CharField(default='Иванов', max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'Новый'), ('pending', 'Рассматривается'), ('accepted', 'Принят'), ('rejected', 'Отказан')], max_length=10)),
                ('beauty_title', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('other_title', models.TextField(blank=True, null=True)),
                ('connect', models.TextField(blank=True, null=True)),
                ('cords', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain3.cords')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain3.image')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain3.level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain3.user')),
            ],
        ),
    ]
